config/routes.rb
Rails.application.routes.draw do
  resources :statentries
  resources :abilities
  resources :units
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability < ApplicationRecord
  has_many :statentries
  has_many :units, through: :statentries
  accepts_nested_attributes_for :units

  validates :name, presence: true
  validates :effect, presence: true
  validates :name, uniqueness: true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/statentry.rb
class Statentry < ApplicationRecord
  belongs_to :unit
  belongs_to :ability
end

app/models/unit.rb
class Unit < ApplicationRecord
  has_many :statentries
  has_many :abilities, through: :statentries
  accepts_nested_attributes_for :abilities
  UNITTYPES = ["Lord", "Legendary Lord", "Hero", "Flying Troop", "Infantry Troop", "Cavalry Troop"]
  SCALES = ["small", "large", "monstrous"]
  validates :name, presence: true
  validates :role, presence: true
  validates :scale, presence: true
  validates :role, inclusion: {in: UNITTYPES}
  validates :scale, inclusion: {in: SCALES}

end

app/controllers/abilities_controller.rb
class AbilitiesController < ApplicationController

  def new
    @ability = Ability.new
  end

  def create
    byebug
    @ability = Ability.new(ability_params)
    if @ability.save

      redirect_to @ability
    else
      #errors
      render :new
    end
  end

  def edit
    @ability = find_ability
  end

  def update
    @ability = find_ability
    if @ability.update(ability_params)
      redirect_to @ability
    else
      #errors
      render :edit
    end
  end

  def show
    @ability = find_ability
  end

  def index
    @abilities = Ability.all
  end

  def destroy
    @ability = find_ability
    @ability.destroy
    redirect_to abilities_path
  end

  private

  def ability_params
    params.require(:ability).permit(:name, :effect, :unit_ids)
  end

  def find_ability
    Ability.find_by(id: params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/statentries_controller.rb
class StatentriesController < ApplicationController

  def new
    @statentry = Statentry.new
  end

  def create
    @statentry = Statentry.new(statentry_params)
    if @statentry.save
      redirect_to @statentry
    else
      #errors
      render :new
    end
  end

  def edit
    @statentry = find_statentry
  end

  def update
    @statentry = find_statentry
    if @statentry.update(statentry_params)
      redirect_to @statentry
    else
      #errors
      render :edit
    end
  end

  def show
    @statentry = find_statentry
  end

  def index
    @statentries = Statentry.all
  end

  def delete
    @statentry = find_statentry
    @statentry.destroy
    redirect_to statentries_path
  end

  private

  def statentry_params
  end

  def find_statentry
  end

end

app/controllers/units_controller.rb
class UnitsController < ApplicationController

  def new
    @unit = Unit.new
    @unit.abilities.new
  end

  def create
    @unit = Unit.new(unit_params)
    if @unit.save
      redirect_to @unit
    else
      #errors
      render :new
    end
  end

  def edit
    @unit = find_unit
  end

  def update
    @unit = find_unit
    if @unit.update(unit_params)
      redirect_to @unit
    else
      #errors
      render :edit
    end
  end

  def show
    @unit = find_unit
  end

  def index
    @units = Unit.all
  end

  def destroy
    @unit = find_unit
    @unit.destroy
    redirect_to units_path
  end

  private

  def unit_params
    params.require(:unit).permit(:name, :scale, :role)
  end

  def find_unit
    Unit.find_by(id: params[:id])
  end

end

app/helpers/abilities_helper.rb
module AbilitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/statentries_helper.rb
module StatentriesHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/abilities/edit.erb
<h1>Editing <%= @ability.name %>: </h1><br><br>
<%= form_for @ability do |f| %>
<%= f.label "Ability Name" %>
<%= f.text_field :name %><br>
<%= f.label "Effect"%>
<%= f.text_area :effect %><br>
<%= f.label "Units with this Ability" %>
<%= f.collection_check_boxes :unit_ids, Unit.all, :id, :name %><br>
<%= f.submit %>
<% end %>
<p></p>
<%= form_for @ability, method: :delete do |f| %>
<%= f.submit "Remove #{@ability.name}" %>
<% end %>

app/views/abilities/index.erb
<h1>Behold all available abilities:</h1>


  <% Ability.all.each do |a| %>
  <p><ul>  <%= link_to a.name, ability_path(a) %>: <%= a.effect %><br>
    <% a.units.each do |u| %>
    <li>Gained by: <%= link_to u.name, unit_path(u) %> </li>
    <% end %>
  </ul>
  </p>
  <% end %>

app/views/abilities/new.erb
<h1> Create a new Ability: </h1><br><br>
<%= form_with model: @ability do |f| %>
<%= f.label "Ability Name" %>
<%= f.text_field :name %><br>
<%= f.label "Effect" %>
<%= f.text_field :effect %><br>
<%= f.label "Units with this Ability:" %>
<%= f.fields_for :units do |ff| %>
  <%= ff.text_field :name %><br>
  <%= ff.text_field :effect %><br>
<% end %>
<%= f.submit %>
<% end %>

app/views/abilities/show.erb
<h1> <%= @ability.name %></h1><br>
<h2> <%= @ability.effect %> </h2><br><br>
Gained by:
<ul>
  <% @ability.units.each do |u| %>
  <li> <%= link_to u.name, unit_path(u) %> </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Capabilities</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/units/edit.erb
<h1>Editing <%= @unit.name %>: </h1><br><br>
<%= form_for @unit do |f| %>
<%= f.label "Unit Name" %>
<%= f.text_field :name %><br>
<%= f.label "Role"%>
<%= f.text_field :role %><br>
<%= f.label "Scale" %>
<%= f.text_field :scale %><br>
<%= f.label "Abilities:" %>
<%= f.collection_check_boxes :abilities, Ability.all, :id, :name %><br>
<%= f.submit %>
<% end %>
<p></p>
<%= form_for @unit, method: :delete do |f| %>
<%= f.submit "Remove #{@unit.name}" %>
<% end %>

app/views/units/index.erb
<h1>The first units I thought of:</h1>


  <% Unit.all.each do |u| %>
  <p><ul>  <%= link_to u.name, unit_path(u) %>: <%= u.scale+" "+u.role %><br>
    <% u.abilities.each do |a| %>
    <li>Abilities: <%= link_to a.name, ability_path(a) %> - <%= a.effect %> </li>
    <% end %>
  </ul>
  </p>
  <% end %>

app/views/units/new.erb
<h1> Create a new Unit: </h1><br><br>
<%= form_for @unit do |f| %>
<%= f.label "Unit Name" %>
<%= f.text_field :name %><br>
<%= f.label "Role" %>
<%= f.text_field :role %><br>
<%= f.label "Scale" %>
<%= f.text_field :scale %><br>
<%= f.label "Abilities:" %>
<%= f.collection_check_boxes :abilities, Ability.all, :id, :name %><br>
<%= f.submit %>
<% end %>

app/views/units/show.erb
<h1> <%= @unit.name %> </h1><br>
<h2> <%= @unit.scale+" "+@unit.role %> </h2><br><br>

Abilities:<br><ul>

<% @unit.abilities.each do |a| %>
<li>  <%= link_to a.name, ability_path(a) %> - <%= a.effect %></li>
<% end %>
</ul>